### ISSUE TITLE
Model performance variance

### ISSUE THREAD

**Issue by LeftThink** [maxiuw/UADA3D#4]
Hello, I tried on nuscenes and kitti domain migration, I use yaml file is the tools/CFGS/custom_models/KittiNU/Centerpoint - M - C.y aml, However, there is a big gap between the results I tested on Nuscenes and those in the paper. I tried to look for corresponding results in the pre-training model provided, but I failed to find the relevant results of Nuscenes and kitti. Could you please provide me with the results? Thank you very much.

**Comment by maxiuw** [comment]
Hi did you correctly compile all datasets? Also did you train for indicated amount of epochs? Also remember that our main model UADA3D is only only with conditional alignment variation. 

Also, have you used the same data augmentation (upsampling/down sampling as we used)? That improves a lot.

The configs for other datasets than Laura and CS-lidar dataset may be not accurate since for larger dataset I migrated to the cluster and I still haven't moved updated configs there.

I will try to update the configs for the other datasets soon
