### ISSUE TITLE
VLD-32  label discrepancy

### ISSUE THREAD

**Issue by LeftThink** [maxiuw/UADA3D#7]
Hello, I have counted the label distribution of VLD-32 in the Lidar-CS dataset as follows:
10,757 Bicyclist
231,373 Car
22,664 Motorcyclist
29,589 Pedestrian
7,984 TrafficCone
33,098 Truck

The labels of VLD-32 in your OneDrive 3DATASETS are as follows:
7,712 Cyclist
18,412 Pedestrian
253,820 Vehicle

These distributions are inconsistent with the original dataset. Could you please explain the reason for this discrepancy?

**Comment by maxiuw** [comment]
Hi
Yes, easy to calculate :) we only detect 3 classes and moved trucks to the vehicle class

**Comment by LeftThink** [comment]
thank you for your reply, why is the Pedestrian different?29,589 Pedestrian
 vs 18,412 Pedestrian

**Comment by maxiuw** [comment]
hmm good point, i do not know why but i think the reason could be filtering per min number of points. I stopped using openpcdet already some time ago but you have some stuff like this in mmdet3d configs where you have min number of points per class. i suspect that's why it can be the reason why there are less objects.

I bet that if you find the place in the code/cfg where this behavior is defined, and switch it to 0, you will get similar behavior.  That's why trucks + vehicles is not exactly the number you woud expect if you merge those 2.

**Comment by LeftThink** [comment]
Thanks for your reply, I will give it a try.
